### ISSUE TITLE
`jest-environment-puppeteer` should include `jest-environment-node` in its dependencies

### ISSUE THREAD

**Issue by lensbart** [smooth-code/jest-puppeteer#396]
Yarn 2 is a bit more strict about it handles dependencies. In particular, all dependencies that a package uses should be listed in its `package.json`. If not, Yarn will tell us that

```
jest-environment-puppeteer tried to access jest-environment-node, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

This error can be overridden by including the following in `.yarnrc.yml`:

```
packageExtensions:
  # awaiting fix: https://github.com/smooth-code/jest-puppeteer/issues/396
  jest-environment-puppeteer@*:
    dependencies:
      jest-environment-node: '*'
```
